version: "3.9"

services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    environment:
      DB_ENGINE: 'postgresql'
      DB_USERNAME: 'marketmetrika_user'
      DB_PASS: 'your_password'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_NAME: 'marketmetrika_db'
      CELERY_BROKER_URL: 'redis://redis:6379/0'  # Add broker URL
    networks:
      - db_network
      - web_network
    depends_on:
      - db
      - redis  # Add redis dependency
    command: >
      sh -c "/wait_for_db.sh && python manage.py makemigrations && python manage.py migrate && daphne -u /tmp/daphne.sock core.asgi:application --verbosity 2"  # Используем daphne

  db:
    image: postgres:13
    container_name: marketmetrika_db
    restart: always
    environment:
      POSTGRES_DB: 'marketmetrika_db'
      POSTGRES_USER: 'marketmetrika_user'
      POSTGRES_PASSWORD: 'your_password'
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Проброс порта на хост

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - db_network
      - web_network

  celery:
    container_name: celery
    restart: always
    build: .
    command: celery -A core worker -l info -B
    environment:
      DB_ENGINE: 'postgresql'
      DB_USERNAME: 'marketmetrika_user'
      DB_PASS: 'your_password'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_NAME: 'marketmetrika_db'
      CELERY_BROKER_URL: 'redis://redis:6379/0'  # Add broker URL
    networks:
      - db_network
      - web_network
    depends_on:
      - db
      - redis

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - appseed-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data:
