# Generated by Django 4.2.9 on 2024-06-15 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('create_time', models.DateTimeField(verbose_name='Время создания')),
                ('change_time', models.DateTimeField(verbose_name='Время изменения')),
                ('search_pluse_state', models.BooleanField(default=False, verbose_name='Состояние поиска Plus')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дневной бюджет')),
                ('advert_id', models.BigIntegerField(verbose_name='ID рекламы')),
                ('status', models.IntegerField(verbose_name='Статус')),
                ('type', models.IntegerField(verbose_name='Тип')),
                ('payment_type', models.CharField(max_length=10, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название меню')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='UnitedParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_cpm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Catalog CPM')),
                ('search_cpm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Search CPM')),
                ('nms', models.JSONField(verbose_name='NMS')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='united_params', to='wildberries.campaign')),
                ('menus', models.ManyToManyField(to='wildberries.menu')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildberries.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название магазина в нашей системе')),
                ('wildberries_name', models.CharField(blank=True, max_length=255, verbose_name='Название магазина в системе Wildberries')),
                ('wildberries_api_key', models.CharField(max_length=512, verbose_name='API ключ Wildberries')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='inactive', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания в нашей системе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildberries.store'),
        ),
    ]
