# Generated by Django 4.2.9 on 2024-06-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atbs', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('cr', models.FloatField()),
                ('shks', models.IntegerField()),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='wildberries.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.IntegerField()),
                ('views', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atbs', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('cr', models.FloatField()),
                ('shks', models.IntegerField()),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='wildberries.campaignstatistic')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atbs', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('cr', models.FloatField()),
                ('shks', models.IntegerField()),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wildberries.platformstatistic')),
            ],
        ),
    ]
