# Generated by Django 4.2.9 on 2024-06-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0002_campaignstatistic_platformstatistic_productstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitedparam',
            name='active_booster',
            field=models.BooleanField(default=False, verbose_name='Active Booster'),
        ),
        migrations.AddField(
            model_name='unitedparam',
            name='active_carousel',
            field=models.BooleanField(default=False, verbose_name='Active Carousel'),
        ),
        migrations.AddField(
            model_name='unitedparam',
            name='active_recom',
            field=models.BooleanField(default=False, verbose_name='Active Recom'),
        ),
    ]
