# Generated by Django 4.2.9 on 2024-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0003_unitedparam_active_booster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название сета')),
            ],
        ),
        migrations.AddField(
            model_name='unitedparam',
            name='nmCPMs',
            field=models.JSONField(default=list, verbose_name='nmCPM'),
        ),
        migrations.AlterField(
            model_name='unitedparam',
            name='nms',
            field=models.JSONField(default=list, verbose_name='NMS'),
        ),
        migrations.AddField(
            model_name='unitedparam',
            name='sets',
            field=models.ManyToManyField(to='wildberries.set'),
        ),
    ]
