# Generated by Django 4.2.9 on 2024-06-21 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0004_set_unitedparam_nmcpms_alter_unitedparam_nms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.JSONField()),
                ('strong', models.JSONField()),
                ('excluded', models.JSONField()),
                ('pluse', models.JSONField()),
                ('fixed', models.BooleanField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_data', to='wildberries.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignKeywordStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_statistics', to='wildberries.campaign')),
            ],
        ),
    ]
