# Generated by Django 4.2.9 on 2024-06-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0005_keyworddata_campaignkeywordstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCampaignKeywordStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('sum', models.FloatField()),
                ('date_recorded', models.DateTimeField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_keyword_statistics', to='wildberries.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'keyword', 'date_recorded')},
            },
        ),
    ]
