# Generated by Django 4.2.9 on 2024-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0007_positiontrackingtask_autobiddersettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobiddersettings',
            name='intra_day_schedule',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='autobiddersettings',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autobiddersettings',
            name='max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='autobiddersettings',
            name='position_ranges',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='autobiddersettings',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autobiddersettings',
            name='weekly_schedule',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
