# Generated by Django 4.2.9 on 2024-07-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0009_remove_autobiddersettings_intra_day_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobiddersettings',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
