# Generated by Django 4.2.9 on 2024-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0012_autobidderlog_bid_autobidderlog_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontrackingtask',
            name='destination',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
