# Generated by Django 4.2.9 on 2024-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0014_autobidderlog_destination_autobidderlog_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobidderlog',
            name='depth',
            field=models.IntegerField(blank=True, default=2, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='autobiddersettings',
            name='depth',
            field=models.IntegerField(blank=True, default=2, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='positiontrackingtask',
            name='depth',
            field=models.IntegerField(blank=True, default=2, max_length=3, null=True),
        ),
    ]
