# Generated by Django 4.2.9 on 2024-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0015_autobidderlog_depth_autobiddersettings_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobiddersettings',
            name='destinations_monitoring',
            field=models.JSONField(default=list, verbose_name='destinations_monitoring'),
        ),
        migrations.AddField(
            model_name='autobiddersettings',
            name='keywords_monitoring',
            field=models.JSONField(default=list, verbose_name='keywords_monitoring'),
        ),
        migrations.AlterField(
            model_name='autobiddersettings',
            name='depth',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
