# Generated by Django 4.2.9 on 2024-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0016_autobiddersettings_destinations_monitoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobidderlog',
            name='depth',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
