# Generated by Django 4.2.9 on 2024-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0017_alter_autobidderlog_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontrackingtask',
            name='dest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='positiontrackingtask',
            name='depth',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
