# Generated by Django 4.2.9 on 2024-07-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0018_positiontrackingtask_dest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positiontrackingtask',
            name='dest',
        ),
    ]
