# Generated by Django 4.2.9 on 2024-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0019_remove_positiontrackingtask_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobidderlog',
            name='cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
