# Generated by Django 4.2.9 on 2024-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0020_autobidderlog_cards_autobidderlog_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstatistic',
            name='actual_atbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignstatistic',
            name='actual_orders',
            field=models.IntegerField(default=0),
        ),
    ]
