# Generated by Django 4.2.9 on 2024-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0022_remove_campaignstatistic_actual_atbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_competitors',
            field=models.JSONField(default=list, verbose_name='advert_competitors'),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_competitors_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_competitors_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_competitors_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='advert_step_costs',
            field=models.JSONField(default=list, verbose_name='advert_step_costs'),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='average_advert_step_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='average_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='before_average_advert_step_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='before_average_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='before_max_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='before_min_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='cpms',
            field=models.JSONField(default=list, verbose_name='cpms'),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='max_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='min_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='position_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autobidderlog',
            name='product_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
