# Generated by Django 4.2.9 on 2024-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0023_autobidderlog_advert_competitors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontrackingtask',
            name='watcher_data',
            field=models.JSONField(default=list, verbose_name='watcher_data'),
        ),
    ]
