# Generated by Django 4.2.9 on 2024-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0024_positiontrackingtask_watcher_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobiddersettings',
            name='keywords_monitoring_add',
            field=models.JSONField(default=list, verbose_name='keywords_monitoring_add'),
        ),
        migrations.AlterField(
            model_name='autobiddersettings',
            name='depth',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
