# Generated by Django 4.2.9 on 2024-09-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0025_autobiddersettings_keywords_monitoring_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyworddata',
            name='additional',
            field=models.JSONField(default=list, verbose_name='additional'),
        ),
    ]
