# Generated by Django 4.2.9 on 2024-12-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0026_keyworddata_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstatistic',
            name='clicks_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignstatistic',
            name='sum_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignstatistic',
            name='views_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='autobidderlog',
            index=models.Index(fields=['destination'], name='destination_idx'),
        ),
        migrations.AddIndex(
            model_name='autobidderlog',
            index=models.Index(fields=['product_id'], name='product_id_idx'),
        ),
    ]
