# Generated by Django 4.2.9 on 2025-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0027_campaignstatistic_clicks_per_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='wildberries_api_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Статус API ключа Wildberries'),
        ),
        migrations.AddField(
            model_name='store',
            name='wildberries_api_status_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
